# Docker configuration from here: https://dev.to/martinpham/symfony-5-development-with-docker-4hj8
version: '3'

services:
  php-fpm:
    build:
      context: ./docker/php-fpm
    environment:
      - DOCKER_ENVIRONMENT=true
      - APP_SECRET=${APP_SECRET}
    volumes:
      - ./:/var/www
  nginx:
    build:
      context: ./docker/nginx
    volumes:
      - ./:/var/www
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/sites/:/etc/nginx/sites-available
      - ./docker/nginx/conf.d/:/etc/nginx/conf.d
      - ./docker/logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "16880:80"
      - "16843:443"
